In [1]:
print("virtual numpy")

virtual numpy


* check numpy version

In [2]:
import numpy as np
print("numpy version : ",np.__version__)   #  numpy version chek

numpy version :  2.4.6


In [3]:
lst=[1,2,3,4,5]
print("This is my 1st list : ",lst)
print(type(lst))
arr=np.array(lst)
print("this is my array : ",arr)    # typecasting -->  change type
print(type(arr))

This is my 1st list :  [1, 2, 3, 4, 5]
<class 'list'>
this is my array :  [1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
lst=list(range(0,20))
print(lst)
arr=np.array(lst)
arr=np.array([5,6,7,8,9])
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


array([5, 6, 7, 8, 9])

In [5]:
lst=np.arange(2,20)
print(lst)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
zero=np.zeros(5)
zero

array([0., 0., 0., 0., 0.])

In [7]:
one=np.ones(7)
one

array([1., 1., 1., 1., 1., 1., 1.])

In [8]:
a=np.linspace(2,10,5)
a

array([ 2.,  4.,  6.,  8., 10.])

In [9]:
arr=np.arange(0,60)
arr
arr=arr.reshape(12,5)      # (row,coloumn)
arr



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [10]:
print(arr.size)    # size 
print(arr.dtype)   # data atype
print(arr.shape)    # shape
print(arr.ndim)   # dimension

60
int64
(12, 5)
2


In [11]:
arr[0,0]   # first row first coloumn

np.int64(0)

In [12]:
arr[-1,-1]    # last row last coloumn

np.int64(59)

In [13]:
arr[11,4]      # last row last coloumn

np.int64(59)

In [14]:
arr[-1,4]      # last row last coloumn

np.int64(59)

In [15]:
arr[11,-1]       # last row last coloumn

np.int64(59)

In [16]:
arr[0]   # first row

array([0, 1, 2, 3, 4])

In [17]:
arr[1]  # second row

array([5, 6, 7, 8, 9])

In [18]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [19]:
arr[3:5]


array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr[7:9,1:3]

array([[36, 37],
       [41, 42]])

In [21]:
arr[10:12,3:5]

array([[53, 54],
       [58, 59]])

In [22]:
arr=np.arange(225)     # 3d array     (3 dimension)
arr=arr.reshape(5,15,3)  #  (table,row,column)  (5 table,15 row,3 colummn)
arr


array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [23]:
arr[0:4,0,0]    # each table ka pahla element

array([  0,  45,  90, 135])

In [24]:
arr[0]  # 1st table

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [25]:
arr[0:5,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [26]:
arr[0:5,0:1]   # each table 1st raw

array([[[  0,   1,   2]],

       [[ 45,  46,  47]],

       [[ 90,  91,  92]],

       [[135, 136, 137]],

       [[180, 181, 182]]])

In [27]:
arr[0:5,-1,-1]  # each table last element

array([ 44,  89, 134, 179, 224])

In [28]:
arr[0:5,0:5]  # each table 5 row

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104]],

       [[135, 136, 137],
        [138, 139, 140],
        [141, 142, 143],
        [144, 145, 146],
        [147, 148, 149]],

       [[180, 181, 182],
        [183, 184, 185],
        [186, 187, 188],
        [189, 190, 191],
        [192, 193, 194]]])

In [29]:
arr[0:5,2]    # each table 3rd row

array([[  6,   7,   8],
       [ 51,  52,  53],
       [ 96,  97,  98],
       [141, 142, 143],
       [186, 187, 188]])

In [30]:
arr[0:5,-1]  # each table last  row

array([[ 42,  43,  44],
       [ 87,  88,  89],
       [132, 133, 134],
       [177, 178, 179],
       [222, 223, 224]])

In [31]:
arr[0:5,-1,0]   # each table ke last row first eleemnt

array([ 42,  87, 132, 177, 222])

In [32]:
arr[0,-1,0]=10   # replace elemnt (42 replace to 10)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 10,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [33]:
print(arr.size)
print(arr.shape)
print(arr.ndim)

225
(5, 15, 3)
3


In [34]:
np.ravel(arr)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  10,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [35]:
arr.flatten()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  10,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18