In [3]:
print("virtual numpy")

virtual numpy


* check numpy version

In [34]:
import numpy as np
print("numpy version : ",np.__version__)   #  numpy version chek

numpy version :  2.4.6


In [ ]:
lst=[1,2,3,4,5]
print("This is my 1st list : ",lst)
print(type(lst))
arr=np.array(lst)
print("this is my array : ",arr)    # typecasting -->  change type
print(type(arr))

This is my 1st list :  [1, 2, 3, 4, 5]
<class 'list'>
this is my array :  [1 2 3 4 5]
<class 'numpy.ndarray'>


In [43]:
lst=list(range(0,20))
print(lst)
arr=np.array(lst)
arr=np.array([5,6,7,8,9])
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


array([5, 6, 7, 8, 9])

In [49]:
lst=np.arange(2,20)
print(lst)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [47]:
zero=np.zeros(5)
zero

array([0., 0., 0., 0., 0.])

In [48]:
one=np.ones(7)
one

array([1., 1., 1., 1., 1., 1., 1.])

In [51]:
a=np.linspace(2,10,5)
a

array([ 2.,  4.,  6.,  8., 10.])

In [79]:
arr=np.arange(0,60)
arr
arr=arr.reshape(12,5)
arr



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [80]:
print(arr.size)    # size 
print(arr.dtype)   # data atype
print(arr.shape)    # shape
print(arr.ndim)   #

60
int64
(12, 5)
2


In [81]:
arr[0,0]   # first row first coloumn

np.int64(0)

In [82]:
arr[-1,-1]    # last row last coloumn

np.int64(59)

In [83]:
arr[11,4]      # last row last coloumn

np.int64(59)

In [84]:
arr[-1,4]      # last row last coloumn

np.int64(59)

In [85]:
arr[11,-1]       # last row last coloumn

np.int64(59)

In [86]:
arr[0]   # first row

array([0, 1, 2, 3, 4])

In [87]:
arr[1]  # second row

array([5, 6, 7, 8, 9])

In [97]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [98]:
arr[3:5]


array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [100]:
arr[7:9,1:3]

array([[36, 37],
       [41, 42]])

In [102]:
arr[10:12,3:5]

array([[53, 54],
       [58, 59]])