In [1]:
print("hello")

hello


In [1]:
import numpy as np

In [ ]:
arr=np.random.randint(1,50,10)  # create random array 1D
arr


array([36, 12, 41, 12, 26,  7, 36, 14, 38,  5], dtype=int32)

In [ ]:
arr=np.random.randint(1,10,(5,6))   # create random array 2D


In [8]:
arr

array([[5, 5, 6, 8, 1, 9],
       [8, 5, 1, 1, 1, 2],
       [6, 3, 2, 1, 7, 4],
       [2, 9, 9, 5, 2, 6],
       [6, 4, 9, 8, 4, 7]], dtype=int32)

In [ ]:
arr=np.arange(1,11)   # create array
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr.sum()

np.int64(55)

In [12]:
arr.max()

np.int64(10)

In [13]:
arr.mean()

np.float64(5.5)

In [ ]:
arr.reshape(2,5)   # make row and coloumn of array (row,column)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [55]:
arr=np.random.randint(1,50,(3,5,4))   # 2D array
arr


array([[[ 2, 41, 35, 17],
        [ 5, 27, 13, 43],
        [11, 47, 13,  1],
        [ 1, 31,  4,  8],
        [21, 33, 36, 35]],

       [[16, 42,  6, 35],
        [41, 47, 26, 27],
        [35,  1, 17,  3],
        [39,  2,  4, 34],
        [ 6, 32,  8, 46]],

       [[21, 31, 30, 27],
        [10, 12, 32, 47],
        [25, 37, 38,  1],
        [11, 40, 32, 33],
        [19, 21, 43, 10]]], dtype=int32)

In [16]:
arr.size

60

In [18]:
arr=np.resize(arr,(20,4))

In [19]:
arr


array([[30, 41, 28,  9],
       [24, 28, 34, 39],
       [11, 23, 22, 11],
       [33, 14, 47, 41],
       [45,  5,  8, 13],
       [18,  4,  9,  6],
       [25, 15, 36, 46],
       [11, 10,  9, 44],
       [ 2,  3, 45,  2],
       [12, 43, 14,  7],
       [ 5, 20,  1, 32],
       [28, 19, 40, 12],
       [46, 28, 30, 35],
       [30, 39, 20, 31],
       [ 4, 43, 46, 22],
       [30, 41, 28,  9],
       [24, 28, 34, 39],
       [11, 23, 22, 11],
       [33, 14, 47, 41],
       [45,  5,  8, 13]], dtype=int32)

In [20]:
arr=np.arange(
    60
).reshape(12,5)

In [21]:
arr.shape

(12, 5)

In [22]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [25]:
arr=np.random.randint(1,20,(5,4))
print(arr)
print(arr*2)   # multiply by 2

[[14 12 16 19]
 [17 10  3 10]
 [13 11 16  4]
 [ 9 19  2  2]
 [12  7 18  7]]
[[28 24 32 38]
 [34 20  6 20]
 [26 22 32  8]
 [18 38  4  4]
 [24 14 36 14]]


In [27]:
arr=np.random.randint(1,20,(5,4))
print(arr)
print(arr/arr)  # divide array to array

[[ 6  1  2  6]
 [10 13 11  2]
 [ 2  9 14  3]
 [ 1 11 19 10]
 [ 9 10  7  4]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
np.transpose(arr)

array([[ 6, 10,  2,  1,  9],
       [ 1, 13,  9, 11, 10],
       [ 2, 11, 14, 19,  7],
       [ 6,  2,  3, 10,  4]], dtype=int32)

In [29]:
arr1=np.random.randint(1,20,(5,4))
arr2=np.random.randint(1,20,(5,1))
print(arr1)
print()
print(arr2)


[[12  8 16  7]
 [15 15  5  6]
 [17 19 13  4]
 [ 4 17 11 16]
 [ 5  9 16  9]]

[[15]
 [ 2]
 [14]
 [ 4]
 [ 5]]


In [31]:
total_arr=np.concatenate((arr1,arr2), axis=1)

In [32]:
total_arr

array([[12,  8, 16,  7, 15],
       [15, 15,  5,  6,  2],
       [17, 19, 13,  4, 14],
       [ 4, 17, 11, 16,  4],
       [ 5,  9, 16,  9,  5]], dtype=int32)

In [33]:
arr1=np.random.randint(1,20,(5,4))
arr2=np.random.randint(1,20,4)
print(arr1)
print()
print(arr2)


[[ 8  1  7 14]
 [ 3  5 19 18]
 [19  7 15  8]
 [13  1 13 11]
 [ 2 14  3 13]]

[11 17  3  1]


In [42]:
np.vstack((arr1,arr2))  # vertical add

array([[ 8,  1,  7, 14],
       [ 3,  5, 19, 18],
       [19,  7, 15,  8],
       [13,  1, 13, 11],
       [ 2, 14,  3, 13],
       [11, 17,  3,  1]], dtype=int32)

In [49]:
arr1=np.random.randint(1,20,(5,4))
arr2=np.random.randint(1,20,(5,4))
print(arr1)
print()
print(arr2)

[[ 8 12  6  3]
 [ 8  4 10 13]
 [18 11 19  6]
 [ 5 16 18 12]
 [15  4 13  6]]

[[ 5  3  7  3]
 [19  9 10 18]
 [13 13 11  3]
 [11 18 16 10]
 [11  5  5  9]]


In [ ]:
np.hstack((arr1,arr2))  # horizontal ad

array([[ 8, 12,  6,  3,  5,  3,  7,  3],
       [ 8,  4, 10, 13, 19,  9, 10, 18],
       [18, 11, 19,  6, 13, 13, 11,  3],
       [ 5, 16, 18, 12, 11, 18, 16, 10],
       [15,  4, 13,  6, 11,  5,  5,  9]], dtype=int32)

In [52]:
#np.hsplit()
#np.vsplit()

In [ ]:
arr1=np.random.randint(1,20,(5,4))
arr2=np.random.randint(1,20,4)
print(arr1)
print()
print(arr2)