In [1]:
print("hello")

hello


In [2]:
import numpy as np

In [3]:
arr=np.random.randint(1,50,10)  # create random array 1D
arr


array([ 6, 32,  9, 43, 17,  4,  8, 40, 36, 24], dtype=int32)

In [4]:
arr=np.random.randint(1,10,(5,6))   # create random array 2D


In [5]:
arr

array([[5, 1, 4, 2, 5, 4],
       [9, 2, 7, 4, 3, 8],
       [1, 7, 2, 2, 3, 2],
       [6, 2, 2, 3, 3, 1],
       [1, 5, 4, 3, 1, 2]], dtype=int32)

In [6]:
arr=np.arange(1,11)   # create array
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr.sum()

np.int64(55)

In [8]:
arr.max()

np.int64(10)

In [9]:
arr.mean()

np.float64(5.5)

In [10]:
arr.reshape(2,5)   # make row and coloumn of array (row,column)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
arr=np.random.randint(1,50,(3,5,4))   # 2D array
arr


array([[[39, 44, 30, 29],
        [ 9,  3,  2, 22],
        [ 9, 45, 42, 12],
        [14, 36, 11,  1],
        [41, 18, 24, 32]],

       [[33, 17, 11, 12],
        [21, 45, 21, 32],
        [45, 25,  2,  2],
        [ 5,  1, 35, 25],
        [ 3, 19, 20, 40]],

       [[35, 36, 11, 14],
        [21,  3, 42, 22],
        [23, 32, 18, 42],
        [16, 29, 35, 41],
        [21,  4,  1, 31]]], dtype=int32)

In [12]:
arr.size

60

In [13]:
arr=np.resize(arr,(20,4))

In [14]:
arr


array([[39, 44, 30, 29],
       [ 9,  3,  2, 22],
       [ 9, 45, 42, 12],
       [14, 36, 11,  1],
       [41, 18, 24, 32],
       [33, 17, 11, 12],
       [21, 45, 21, 32],
       [45, 25,  2,  2],
       [ 5,  1, 35, 25],
       [ 3, 19, 20, 40],
       [35, 36, 11, 14],
       [21,  3, 42, 22],
       [23, 32, 18, 42],
       [16, 29, 35, 41],
       [21,  4,  1, 31],
       [39, 44, 30, 29],
       [ 9,  3,  2, 22],
       [ 9, 45, 42, 12],
       [14, 36, 11,  1],
       [41, 18, 24, 32]], dtype=int32)

In [15]:
arr=np.arange(
    60
).reshape(12,5)

In [16]:
arr.shape

(12, 5)

In [17]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [18]:
arr=np.random.randint(1,20,(5,4))
print(arr)
print(arr*2)   # multiply by 2

[[ 9  6  2  5]
 [11 14  4  6]
 [ 4  3 19  9]
 [12 11 19 14]
 [ 3  8  7  7]]
[[18 12  4 10]
 [22 28  8 12]
 [ 8  6 38 18]
 [24 22 38 28]
 [ 6 16 14 14]]


In [19]:
arr=np.random.randint(1,20,(5,4))
print(arr)
print(arr/arr)  # divide array to array

[[ 1 14 15  8]
 [13 17 18 18]
 [ 6  6 16 16]
 [15  8 15 13]
 [ 6 15  5 13]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
np.transpose(arr)

array([[ 1, 13,  6, 15,  6],
       [14, 17,  6,  8, 15],
       [15, 18, 16, 15,  5],
       [ 8, 18, 16, 13, 13]], dtype=int32)

In [21]:
arr1=np.random.randint(1,20,(5,4))
arr2=np.random.randint(1,20,(5,1))
print(arr1)
print()
print(arr2)


[[16  7 10 11]
 [ 1 16 12 19]
 [16 19 18 18]
 [ 7 18 13  1]
 [12  2 15  8]]

[[14]
 [ 1]
 [ 1]
 [14]
 [13]]


In [22]:
total_arr=np.concatenate((arr1,arr2), axis=1)    # write two array in one array

In [23]:
total_arr

array([[16,  7, 10, 11, 14],
       [ 1, 16, 12, 19,  1],
       [16, 19, 18, 18,  1],
       [ 7, 18, 13,  1, 14],
       [12,  2, 15,  8, 13]], dtype=int32)

In [24]:
arr1=np.random.randint(1,20,(5,4))
arr2=np.random.randint(1,20,4)
print(arr1)
print()
print(arr2)


[[14 10 17  5]
 [10 18 10 16]
 [10  3 18  6]
 [ 3  5  5 14]
 [ 2  1  9 13]]

[ 9  6 16  6]


In [25]:
np.vstack((arr1,arr2))  # vertical add

array([[14, 10, 17,  5],
       [10, 18, 10, 16],
       [10,  3, 18,  6],
       [ 3,  5,  5, 14],
       [ 2,  1,  9, 13],
       [ 9,  6, 16,  6]], dtype=int32)

In [26]:
arr1=np.random.randint(1,20,(5,4))
arr2=np.random.randint(1,20,(5,4))
print(arr1)
print()
print(arr2)

[[17  4  8 14]
 [ 2  4 14 11]
 [ 3  8 18  2]
 [ 3 19 12  8]
 [16  4 16 14]]

[[ 9  1 19  4]
 [17 11 10  6]
 [12  1 11 17]
 [16  4  9 13]
 [ 6 17  4  8]]


In [27]:
np.hstack((arr1,arr2))  # horizontal ad

array([[17,  4,  8, 14,  9,  1, 19,  4],
       [ 2,  4, 14, 11, 17, 11, 10,  6],
       [ 3,  8, 18,  2, 12,  1, 11, 17],
       [ 3, 19, 12,  8, 16,  4,  9, 13],
       [16,  4, 16, 14,  6, 17,  4,  8]], dtype=int32)

In [28]:
#np.hsplit()
#np.vsplit()

In [29]:
arr1=np.random.randint(1,20,(5,4))
arr2=np.random.randint(1,20,4)
print(arr1)
print()
print(arr2)

[[ 8 11  5 17]
 [ 7 15  7  9]
 [ 5  3  2  3]
 [12 13  4  6]
 [18  1  5  6]]

[14 15  5 17]
